package com.wontlost.ckeditor.generator;

import com.wontlost.ckeditor.CKEditorPlugin;
import com.wontlost.ckeditor.domain.BuilderState;
import com.wontlost.ckeditor.domain.BuilderState.CodeBlockLanguageConfig;
import com.wontlost.ckeditor.domain.BuilderState.CustomPluginConfig;
import com.wontlost.ckeditor.domain.BuilderState.MentionFeedConfig;
import com.wontlost.ckeditor.domain.BuilderState.ToolbarStyleConfig;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * Java Code Generator
 * Generates Vaadin CKEditor Java configuration code
 */
public class JavaCodeGenerator implements CodeGenerator {

    private static final DateTimeFormatter TIMESTAMP_FORMAT =
        DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    @Override
    public String generate(BuilderState state) {
        StringBuilder sb = new StringBuilder();
        String timestamp = LocalDateTime.now().format(TIMESTAMP_FORMAT);

        // File header comment
        sb.append("// VaadinCKEditor Configuration\n");
        sb.append("// Generated by CKEditor Builder at ").append(timestamp).append("\n");
        sb.append("// https://github.com/wontlost-ltd/vaadin-ckeditor\n");
        sb.append("// Open Source + Commercial Support\n");
        sb.append("//\n");
        sb.append("// Toolbar Display Mode:\n");
        sb.append("// - Multi-line (default): config.setToolbar(items, true)  - All buttons visible\n");
        sb.append("// - Single-line: config.setToolbar(items, false) - Overflow goes to menu\n\n");

        // Import statements
        generateImports(sb, state);

        // Generate CKEditorConfig (if advanced config exists)
        if (hasAdvancedConfig(state)) {
            generateConfigCode(sb, state);
            sb.append("\n");
        }

        // Create editor using Builder API
        generateBuilderCode(sb, state);

        // Add to layout example
        sb.append("\n// Add to layout\n");
        sb.append("add(editor);\n");

        // Event listener examples
        generateEventListenerCode(sb, state);

        // Custom CSS example (if any)
        if (state.getCustomCss() != null && !state.getCustomCss().isEmpty()) {
            sb.append("\n");
            generateCustomCssCode(sb, state);
        }

        return sb.toString();
    }

    private void generateImports(StringBuilder sb, BuilderState state) {
        sb.append("import com.wontlost.ckeditor.*;\n");

        if (hasAdvancedConfig(state)) {
            sb.append("import com.wontlost.ckeditor.CKEditorConfig;\n");
        }

        if (state.getToolbarStyle() != null && state.getToolbarStyle().hasAnyStyle()) {
            sb.append("import com.wontlost.ckeditor.ToolbarStyle;\n");
        }

        if (!state.getPremiumPlugins().isEmpty() || !state.getCustomPlugins().isEmpty()) {
            sb.append("import com.wontlost.ckeditor.CustomPlugin;\n");
        }

        if (state.getDependencyMode() != BuilderState.DependencyMode.AUTO_RESOLVE) {
            sb.append("import com.wontlost.ckeditor.DependencyMode;\n");
        }

        sb.append("\n");
    }

    private boolean hasAdvancedConfig(BuilderState state) {
        return (state.getPlaceholder() != null && !state.getPlaceholder().isEmpty()) ||
               !state.getFontSizes().isEmpty() ||
               !state.getFontFamilies().isEmpty() ||
               !state.getSimpleUploadUrl().isEmpty() ||
               !state.getImageToolbar().isEmpty() ||
               !state.getTableContentToolbar().isEmpty() ||
               !state.getMentionFeeds().isEmpty() ||
               !state.getCodeBlockLanguages().isEmpty() ||
               !state.getToolbarItems().isEmpty() ||
               (state.getToolbarStyle() != null && state.getToolbarStyle().hasAnyStyle());
    }

    private void generateConfigCode(StringBuilder sb, BuilderState state) {
        sb.append("// CKEditor Advanced Configuration\n");
        sb.append("CKEditorConfig config = new CKEditorConfig()");

        // Placeholder
        if (state.getPlaceholder() != null && !state.getPlaceholder().isEmpty()) {
            sb.append("\n    .withCustomConfig(\"placeholder\", \"")
              .append(escapeJavaString(state.getPlaceholder())).append("\")");
        }

        // Font Sizes
        if (!state.getFontSizes().isEmpty()) {
            sb.append("\n    .withFontSizes(new String[]{")
              .append(state.getFontSizes().stream()
                  .map(s -> "\"" + escapeJavaString(s.trim()) + "\"")
                  .collect(Collectors.joining(", ")))
              .append("})");
        }

        // Font Families
        if (!state.getFontFamilies().isEmpty()) {
            sb.append("\n    .withFontFamilies(new String[]{")
              .append(state.getFontFamilies().stream()
                  .map(s -> "\"" + escapeJavaString(s.trim()) + "\"")
                  .collect(Collectors.joining(", ")))
              .append("})");
        }

        // Link Configuration
        if (!state.getLinkDefaultProtocol().equals("https://")) {
            sb.append("\n    .withLinkDefaultProtocol(\"")
              .append(escapeJavaString(state.getLinkDefaultProtocol())).append("\")");
        }

        // Simple Upload
        if (!state.getSimpleUploadUrl().isEmpty()) {
            sb.append("\n    .withImageUploadUrl(\"")
              .append(escapeJavaString(state.getSimpleUploadUrl())).append("\")");
        }

        // Image Toolbar
        if (!state.getImageToolbar().isEmpty()) {
            sb.append("\n    .withImageToolbar(new String[]{")
              .append(state.getImageToolbar().stream()
                  .map(s -> "\"" + escapeJavaString(s.trim()) + "\"")
                  .collect(Collectors.joining(", ")))
              .append("})");
        }

        // Table Content Toolbar
        if (!state.getTableContentToolbar().isEmpty()) {
            sb.append("\n    .withTableContentToolbar(new String[]{")
              .append(state.getTableContentToolbar().stream()
                  .map(s -> "\"" + escapeJavaString(s.trim()) + "\"")
                  .collect(Collectors.joining(", ")))
              .append("})");
        }

        // Toolbar configuration with multi-line display mode
        // shouldNotGroupWhenFull = true means all buttons visible (multi-line)
        // shouldNotGroupWhenFull = false means overflow goes to ⋮ menu (single-line)
        if (!state.getToolbarItems().isEmpty()) {
            sb.append("\n    // Toolbar config: 2nd param true=multi-line, false=single-line (overflow to menu)\n");
            sb.append("    .setToolbar(new String[]{")
              .append(state.getToolbarItems().stream()
                  .map(s -> "\"" + escapeJavaString(s.trim()) + "\"")
                  .collect(Collectors.joining(", ")))
              .append("}, true)");
        }

        // Code Block Languages
        if (!state.getCodeBlockLanguages().isEmpty()) {
            sb.append("\n    .withCodeBlockLanguages(new String[][]{");
            for (int i = 0; i < state.getCodeBlockLanguages().size(); i++) {
                CodeBlockLanguageConfig lang = state.getCodeBlockLanguages().get(i);
                if (i > 0) sb.append(", ");
                sb.append("{\"").append(escapeJavaString(lang.getLanguage())).append("\", \"")
                  .append(escapeJavaString(lang.getLabel())).append("\"}");
            }
            sb.append("})");
        }

        // Toolbar Style
        ToolbarStyleConfig toolbarStyle = state.getToolbarStyle();
        if (toolbarStyle != null && toolbarStyle.hasAnyStyle()) {
            sb.append("\n    .setToolbarStyle(ToolbarStyle.builder()");
            if (toolbarStyle.getBackground() != null) {
                sb.append("\n        .background(\"").append(escapeJavaString(toolbarStyle.getBackground())).append("\")");
            }
            if (toolbarStyle.getBorderColor() != null) {
                sb.append("\n        .borderColor(\"").append(escapeJavaString(toolbarStyle.getBorderColor())).append("\")");
            }
            if (toolbarStyle.getBorderRadius() != null) {
                sb.append("\n        .borderRadius(\"").append(escapeJavaString(toolbarStyle.getBorderRadius())).append("\")");
            }
            if (toolbarStyle.getButtonBackground() != null) {
                sb.append("\n        .buttonBackground(\"").append(escapeJavaString(toolbarStyle.getButtonBackground())).append("\")");
            }
            if (toolbarStyle.getButtonHoverBackground() != null) {
                sb.append("\n        .buttonHoverBackground(\"").append(escapeJavaString(toolbarStyle.getButtonHoverBackground())).append("\")");
            }
            if (toolbarStyle.getButtonActiveBackground() != null) {
                sb.append("\n        .buttonActiveBackground(\"").append(escapeJavaString(toolbarStyle.getButtonActiveBackground())).append("\")");
            }
            if (toolbarStyle.getButtonOnBackground() != null) {
                sb.append("\n        .buttonOnBackground(\"").append(escapeJavaString(toolbarStyle.getButtonOnBackground())).append("\")");
            }
            if (toolbarStyle.getButtonOnColor() != null) {
                sb.append("\n        .buttonOnColor(\"").append(escapeJavaString(toolbarStyle.getButtonOnColor())).append("\")");
            }
            if (toolbarStyle.getIconColor() != null) {
                sb.append("\n        .iconColor(\"").append(escapeJavaString(toolbarStyle.getIconColor())).append("\")");
            }
            sb.append("\n        .build())");
        }

        sb.append(";\n");
    }

    private void generateBuilderCode(StringBuilder sb, BuilderState state) {
        sb.append("// Create editor using Builder API\n");
        sb.append("VaadinCKEditor editor = VaadinCKEditor.create()\n");
        sb.append("    .withPreset(CKEditorPreset.").append(state.getPreset().name()).append(")\n");
        sb.append("    .withType(CKEditorType.").append(state.getEditorType().name()).append(")\n");
        sb.append("    .withTheme(CKEditorTheme.").append(state.getTheme().name()).append(")\n");
        sb.append("    .withLanguage(\"").append(escapeJavaString(state.getLanguage())).append("\")\n");
        sb.append("    .withWidth(\"").append(escapeJavaString(state.getEditorWidth())).append("\")\n");
        sb.append("    .withHeight(\"").append(escapeJavaString(state.getEditorHeight())).append("\")");

        // License Key
        if (state.hasLicenseKey()) {
            sb.append("\n    // Recommended: Get License Key from environment variable\n");
            sb.append("    .withLicenseKey(System.getenv(\"CKEDITOR_LICENSE_KEY\"))");
        }

        // CKEditorConfig
        if (hasAdvancedConfig(state)) {
            sb.append("\n    .withConfig(config)");
        }

        // Dependency Mode
        if (state.getDependencyMode() != BuilderState.DependencyMode.AUTO_RESOLVE) {
            sb.append("\n    .withDependencyMode(DependencyMode.")
              .append(state.getDependencyMode().name()).append(")");
        }

        // Premium Plugins
        for (CustomPluginConfig plugin : state.getPremiumPlugins()) {
            sb.append("\n    .addCustomPlugin(CustomPlugin.fromPremium(\"")
              .append(escapeJavaString(plugin.getName())).append("\")");
            if (!plugin.getToolbarItems().isEmpty()) {
                sb.append("\n        .withToolbarItems(")
                  .append(plugin.getToolbarItems().stream()
                      .map(t -> "\"" + escapeJavaString(t) + "\"")
                      .collect(Collectors.joining(", ")))
                  .append(")");
            }
            sb.append(")");
        }

        // Custom Plugins
        for (CustomPluginConfig plugin : state.getCustomPlugins()) {
            sb.append("\n    .addCustomPlugin(CustomPlugin.builder(\"")
              .append(escapeJavaString(plugin.getName())).append("\")\n");
            sb.append("        .withImportPath(\"").append(escapeJavaString(plugin.getImportPath())).append("\")");
            if (!plugin.getToolbarItems().isEmpty()) {
                sb.append("\n        .withToolbarItems(")
                  .append(plugin.getToolbarItems().stream()
                      .map(t -> "\"" + escapeJavaString(t) + "\"")
                      .collect(Collectors.joining(", ")))
                  .append(")");
            }
            sb.append("\n        .build())");
        }

        // Read Only
        if (state.isReadOnly()) {
            sb.append("\n    .readOnly(true)");
        }

        // Initial Value
        if (state.getInitialValue() != null && !state.getInitialValue().isEmpty()) {
            sb.append("\n    .withValue(\"").append(escapeJavaString(state.getInitialValue())).append("\")");
        }

        // Note: Toolbar is configured in config.setToolbar() (includes shouldNotGroupWhenFull option)
        // Don't use .withToolbar() to avoid overriding config settings

        sb.append("\n    .build();\n");

        // Post-build configurations
        generatePostBuildConfig(sb, state);
    }

    private void generatePostBuildConfig(StringBuilder sb, BuilderState state) {
        // GHS
        if (state.isGhsEnabled()) {
            sb.append("\n// Enable General HTML Support\n");
            sb.append("editor.setGhsEnabled(true);\n");
        }

        // Minimap (for Decoupled editor)
        if (state.isMinimapEnabled()) {
            sb.append("\n// Enable Minimap (Decoupled mode only)\n");
            sb.append("editor.setMinimapEnabled(true);\n");
        }

        // Hide Toolbar (for View Only mode)
        if (state.isHideToolbar() || state.isViewOnly()) {
            sb.append("\n// Hide toolbar\n");
            sb.append("editor.setToolbarHidden(true);\n");
        }
    }

    private void generateEventListenerCode(StringBuilder sb, BuilderState state) {
        sb.append("\n// Listen for content changes\n");
        sb.append("editor.addValueChangeListener(event -> {\n");
        sb.append("    String content = event.getValue();\n");
        sb.append("    // Handle content change\n");
        sb.append("});\n");

        // Autosave
        if (state.isAutosaveEnabled()) {
            sb.append("\n// Autosave configuration\n");
            sb.append("editor.addAutosaveListener(content -> {\n");
            sb.append("    // Save content to database\n");
            sb.append("    saveToDatabase(content);\n");
            sb.append("}, ").append(state.getAutosaveInterval()).append("); // ")
              .append(state.getAutosaveInterval() / 1000).append("s debounce\n");
        }

        // Upload Handler (if upload URL is configured)
        if (!state.getSimpleUploadUrl().isEmpty()) {
            sb.append("\n// File upload handler (optional, for custom handling logic)\n");
            sb.append("editor.addUploadHandler((file, mimeType) -> {\n");
            sb.append("    // Validate file\n");
            sb.append("    if (file.length > ").append(state.getUploadMaxFileSize()).append("L) {\n");
            sb.append("        throw new RuntimeException(\"File too large\");\n");
            sb.append("    }\n");
            sb.append("    // Upload and return URL\n");
            sb.append("    return uploadService.upload(file, mimeType);\n");
            sb.append("});\n");
        }
    }

    private void generateCustomCssCode(StringBuilder sb, BuilderState state) {
        sb.append("// ═══════════════════════════════════════════════════════════════════\n");
        sb.append("// Custom CSS Injection Guide\n");
        sb.append("// ═══════════════════════════════════════════════════════════════════\n");
        sb.append("// Method 1: JavaScript dynamic injection (recommended for runtime styles)\n");
        sb.append("//   Pros: Flexible, can be modified dynamically\n");
        sb.append("//   Cons: Requires waiting for editor initialization\n");
        sb.append("//\n");
        sb.append("// Method 2: CSS file import (recommended for static styles)\n");
        sb.append("//   1. Save CSS to frontend/themes/your-theme/styles.css\n");
        sb.append("//   2. Vaadin project will auto-load theme styles\n");
        sb.append("//\n");
        sb.append("// Method 3: @CssImport annotation\n");
        sb.append("//   @CssImport(\"./styles/ckeditor-custom.css\")\n");
        sb.append("//   public class YourView extends VerticalLayout { ... }\n");
        sb.append("// ═══════════════════════════════════════════════════════════════════\n\n");

        sb.append("// Method 1: Inject CSS via JavaScript\n");
        sb.append("String customCss = \"\"\"\n");
        // Format CSS for readability, escape text block delimiters
        String css = escapeTextBlock(state.getCustomCss());
        for (String line : css.split("\n")) {
            sb.append("    ").append(line).append("\n");
        }
        sb.append("    \"\"\";\n\n");

        sb.append("editor.getElement().executeJs(\n");
        sb.append("    \"\"\"(\n");
        sb.append("    function(el, css) {\n");
        sb.append("        var style = document.createElement('style');\n");
        sb.append("        style.setAttribute('data-custom-css', 'true');\n");
        sb.append("        style.textContent = css;\n");
        sb.append("        if (el.shadowRoot) {\n");
        sb.append("            el.shadowRoot.appendChild(style);\n");
        sb.append("        } else {\n");
        sb.append("            document.head.appendChild(style);\n");
        sb.append("        }\n");
        sb.append("    })($0, $1)\n");
        sb.append("    \"\"\",\n");
        sb.append("    editor.getElement(),\n");
        sb.append("    customCss\n");
        sb.append(");\n");
    }

    private String escapeJavaString(String str) {
        if (str == null) return "";
        return str.replace("\\", "\\\\")
                  .replace("\"", "\\\"")
                  .replace("\n", "\\n")
                  .replace("\r", "\\r")
                  .replace("\t", "\\t")
                  .replace("\0", "\\0")
                  .replace("\f", "\\f")
                  .replace("\b", "\\b");
    }

    /**
     * 转义 Java 文本块（text block）中的特殊序列
     * 防止用户 CSS 中出现 \""" 终结符导致代码注入
     */
    private String escapeTextBlock(String str) {
        if (str == null) return "";
        return str.replace("\\", "\\\\")
                  .replace("\"\"\"", "\\\"\"\"");
    }

    @Override
    public String getFileExtension() {
        return "java";
    }

    @Override
    public String getDisplayName() {
        return "Java";
    }

    @Override
    public String getMimeType() {
        return "text/x-java-source";
    }
}
