package com.wontlost.ckeditor.generator;

import com.wontlost.ckeditor.CKEditorPlugin;
import com.wontlost.ckeditor.domain.BuilderState;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.stream.Collectors;

/**
 * TypeScript Code Generator
 * Generates TypeScript configuration code for frontend use
 */
public class TypeScriptCodeGenerator implements CodeGenerator {

    private static final DateTimeFormatter TIMESTAMP_FORMAT =
        DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    @Override
    public String generate(BuilderState state) {
        StringBuilder sb = new StringBuilder();
        String timestamp = LocalDateTime.now().format(TIMESTAMP_FORMAT);

        // File header comment
        sb.append("// VaadinCKEditor TypeScript Configuration\n");
        sb.append("// Generated by CKEditor Builder at ").append(timestamp).append("\n");
        sb.append("// Open Source + Commercial Support\n");
        sb.append("//\n");
        sb.append("// Toolbar Display Mode:\n");
        sb.append("// - Multi-line: shouldNotGroupWhenFull: true  - All buttons visible\n");
        sb.append("// - Single-line: shouldNotGroupWhenFull: false - Overflow goes to menu\n\n");

        // Import statements
        sb.append("import type { CKEditorPreset, CKEditorType, CKEditorTheme } from '@vaadin/ckeditor';\n\n");

        // Type definition
        generateTypeDefinition(sb);

        // Configuration object
        generateConfigObject(sb, state);

        // Plugin list
        generatePluginsList(sb, state);

        // Toolbar configuration
        generateToolbarConfig(sb, state);

        // Custom CSS
        if (state.getCustomCss() != null && !state.getCustomCss().isEmpty()) {
            sb.append("\n");
            generateCustomCss(sb, state);
        }

        // Exports
        sb.append("\nexport { editorConfig, plugins, toolbar");
        if (state.getCustomCss() != null && !state.getCustomCss().isEmpty()) {
            sb.append(", customStyles");
        }
        sb.append(" };\n");
        sb.append("export default editorConfig;\n");

        return sb.toString();
    }

    private void generateTypeDefinition(StringBuilder sb) {
        sb.append("/**\n");
        sb.append(" * CKEditor Configuration Interface\n");
        sb.append(" */\n");
        sb.append("interface EditorConfig {\n");
        sb.append("  preset: CKEditorPreset;\n");
        sb.append("  type: CKEditorType;\n");
        sb.append("  theme: CKEditorTheme;\n");
        sb.append("  language: string;\n");
        sb.append("  width: string;\n");
        sb.append("  height: string;\n");
        sb.append("}\n\n");
    }

    private void generateConfigObject(StringBuilder sb, BuilderState state) {
        sb.append("/**\n");
        sb.append(" * Editor Base Configuration\n");
        sb.append(" */\n");
        sb.append("const editorConfig: EditorConfig = {\n");
        sb.append("  preset: '").append(state.getPreset().name()).append("' as CKEditorPreset,\n");
        sb.append("  type: '").append(state.getEditorType().name()).append("' as CKEditorType,\n");
        sb.append("  theme: '").append(state.getTheme().name()).append("' as CKEditorTheme,\n");
        sb.append("  language: '").append(escapeSingleQuoteString(state.getLanguage())).append("',\n");
        sb.append("  width: '100%',\n");
        sb.append("  height: '400px',\n");
        sb.append("};\n");
    }

    private void generatePluginsList(StringBuilder sb, BuilderState state) {
        sb.append("\n/**\n");
        sb.append(" * Enabled Plugins List\n");
        sb.append(" */\n");
        sb.append("const plugins: string[] = [\n");

        List<String> plugins = state.getSelectedPlugins().stream()
            .map(p -> "  '" + escapeSingleQuoteString(p.getJsName()) + "'")
            .collect(Collectors.toList());
        sb.append(String.join(",\n", plugins));

        sb.append("\n];\n");
    }

    private void generateToolbarConfig(StringBuilder sb, BuilderState state) {
        sb.append("\n/**\n");
        sb.append(" * Toolbar Configuration\n");
        sb.append(" * shouldNotGroupWhenFull: true  - Multi-line, all buttons visible\n");
        sb.append(" * shouldNotGroupWhenFull: false - Single-line, overflow goes to menu\n");
        sb.append(" */\n");
        sb.append("const toolbar = {\n");
        sb.append("  items: [\n");

        if (!state.getToolbarItems().isEmpty()) {
            List<String> items = state.getToolbarItems().stream()
                .map(t -> "    '" + escapeSingleQuoteString(t) + "'")
                .collect(Collectors.toList());
            sb.append(String.join(",\n", items));
        } else {
            // Generate default toolbar based on plugins
            List<String> defaultItems = state.getSelectedPlugins().stream()
                .flatMap(p -> p.getToolbarItems().stream())
                .distinct()
                .map(t -> "    '" + escapeSingleQuoteString(t) + "'")
                .collect(Collectors.toList());
            sb.append(String.join(",\n", defaultItems));
        }

        sb.append("\n  ],\n");
        sb.append("  shouldNotGroupWhenFull: true  // Set to false for single-line mode\n");
        sb.append("};\n");
    }

    private void generateCustomCss(StringBuilder sb, BuilderState state) {
        sb.append("// ═══════════════════════════════════════════════════════════════════\n");
        sb.append("// Custom CSS Usage Guide\n");
        sb.append("// ═══════════════════════════════════════════════════════════════════\n");
        sb.append("// Method 1: JavaScript dynamic injection (for runtime styles)\n");
        sb.append("//   const style = document.createElement('style');\n");
        sb.append("//   style.textContent = customStyles;\n");
        sb.append("//   document.head.appendChild(style);\n");
        sb.append("//\n");
        sb.append("// Method 2: CSS file import (recommended for static styles)\n");
        sb.append("//   Save the CSS below to a separate .css file and import in HTML\n");
        sb.append("//   <link rel=\"stylesheet\" href=\"./ckeditor-custom.css\">\n");
        sb.append("//\n");
        sb.append("// Method 3: CSS-in-JS libraries (styled-components, emotion, etc.)\n");
        sb.append("// ═══════════════════════════════════════════════════════════════════\n\n");

        sb.append("/**\n");
        sb.append(" * Custom Styles\n");
        sb.append(" * Can be saved as a .css file or injected via JavaScript\n");
        sb.append(" */\n");
        sb.append("const customStyles: string = `\n");
        sb.append(escapeTemplateLiteral(state.getCustomCss()));
        sb.append("\n`;\n\n");

        sb.append("// Function to inject styles dynamically\n");
        sb.append("function injectCustomStyles(): void {\n");
        sb.append("  const style = document.createElement('style');\n");
        sb.append("  style.setAttribute('data-custom-css', 'ckeditor');\n");
        sb.append("  style.textContent = customStyles;\n");
        sb.append("  document.head.appendChild(style);\n");
        sb.append("}\n\n");
        sb.append("// Call after editor initialization\n");
        sb.append("// injectCustomStyles();\n");
    }

    /**
     * 转义 TypeScript 模板字面量中的特殊字符
     * 防止反引号和 ${} 表达式注入
     */
    private String escapeTemplateLiteral(String str) {
        if (str == null) return "";
        return str.replace("\\", "\\\\")
                  .replace("`", "\\`")
                  .replace("${", "\\${");
    }

    /**
     * 转义 TypeScript 单引号字符串中的特殊字符
     */
    private String escapeSingleQuoteString(String str) {
        if (str == null) return "";
        return str.replace("\\", "\\\\")
                  .replace("'", "\\'")
                  .replace("\n", "\\n")
                  .replace("\r", "\\r");
    }

    @Override
    public String getFileExtension() {
        return "ts";
    }

    @Override
    public String getDisplayName() {
        return "TypeScript";
    }

    @Override
    public String getMimeType() {
        return "application/typescript";
    }
}
